// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nrrvcgcptlczalbeyfbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ycnZjZ2NwdGxjemFsYmV5ZmJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYyNTM4NzQsImV4cCI6MjA4MTgyOTg3NH0.JadeWrpOrQzIRo8mo0uUuzFD73n2N35ExemfU5Xc03A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});